=== aycaRichard12/CtrCobrosPagos/cliente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="cliente" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="cliente">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="idcliente " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA+0QdNuhMcSpqyma73ynjVAAAAAFzVMPe1Z+ZAAAAAAAAAAABjAGwA
aQBlAG4AdABlAAAAAAAAAAJWKvszo8BNo/t3bUs4vrwAAAAAZ1gpywxo5kAAAAAA
AAAAAGkAbgBnAHIAZQBzAG8AAAAAAAAANK2cW3bxAkWDBl1etp3JVQcAAAA+0QdN
uhMcSpqyma73ynjVaQBkAGMAbABpAGUAbgB0AGUAAAAAAAAAMWoKJH6CN0yIcNyd
qXDCggcAAAA+0QdNuhMcSpqyma73ynjVbgBvAG0AYgByAGUAAAAAAAAA+lpeV8Px
30ecN3G6qBhhYQcAAAA+0QdNuhMcSpqyma73ynjVZABlAHMAYwByAGkAcABjAGkA
bwBuAAAAAAAAAJ8C1Ez55X5Dkjv72sLeHMEHAAAAPtEHTboTHEqaspmu98p41XQA
ZQBsAGUAZgBvAG4AbwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAA
AAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="PtEHTboTHEqaspmu98p41Q==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idcliente" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="NK2cW3bxAkWDBl1etp3JVQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="nombre" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="MWoKJH6CN0yIcNydqXDCgg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2868"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="descripcion" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="+lpeV8Px30ecN3G6qBhhYQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1668"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="telefono" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nwLUTPnlfkOSO/vawt4cwQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== aycaRichard12/CtrCobrosPagos/cliente.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="cliente.xsd" generated="2025-09-06T08:03:41">
<cliente>
<idcliente>29</idcliente>
<nombre>LISBETH (ENTRE RIOS) </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>30</idcliente>
<nombre>BLANCA (IVIRGARZAMA) </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>31</idcliente>
<nombre>HILDA (SHINAOTA) </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>32</idcliente>
<nombre>REYNALDO (VENTAS)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>33</idcliente>
<nombre>COMERCIAL BEIJING</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>34</idcliente>
<nombre>ROLANDO QUISPE (EL ALTO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>35</idcliente>
<nombre>JULIO ROQUE (YACUIBA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>36</idcliente>
<nombre>JUAN JOSE MAMANI (EL ALTO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>37</idcliente>
<nombre>GABINO JUSTO (EL ALTO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>38</idcliente>
<nombre>GONZALO LOPEZ (ELECTRODO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>39</idcliente>
<nombre>BERTO JIMENEZ (VALLE GRANDE)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>40</idcliente>
<nombre>AMADEO CUENCA FLORES (ELECTRODO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>41</idcliente>
<nombre>FERNANDO BARRERA (INOX)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>42</idcliente>
<nombre>ORLANDO MAMANI (VILLAZON)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>43</idcliente>
<nombre>ALEX SIGUARIO (TARIJA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>44</idcliente>
<nombre>AMERICO PEREZ (INOX)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>45</idcliente>
<nombre>JUAN CONTRERAS (LA PAZ)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>46</idcliente>
<nombre>JOSE MAMANI (LLALLAGUA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>47</idcliente>
<nombre>MICHAEL VILLALOBOS (EL ALTO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>48</idcliente>
<nombre>FELICIANO AGUILAR (ALAMBRE MIG)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>49</idcliente>
<nombre>GARY VALERO (PINTURA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>50</idcliente>
<nombre>ALEXANDRE LOPEZ (INOX)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>51</idcliente>
<nombre>VALERIO JARJURI</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>52</idcliente>
<nombre>NOEMI MONTAÑO</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>53</idcliente>
<nombre>JULIO ROQUE (YACUIBA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>54</idcliente>
<nombre>EDSON METALINOX </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>55</idcliente>
<nombre>ERNESTO GARCIA (AYACUCHO)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>56</idcliente>
<nombre>ERNESTO (SHINAOTA) </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>57</idcliente>
<nombre>HILARIA CRUZ (MIZQUE)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>58</idcliente>
<nombre>GENOVEVA MACHADO (ENTRE RIOS)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>59</idcliente>
<nombre>COMERCIAL FLORES</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>60</idcliente>
<nombre>OMAR (YAPACANI)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>61</idcliente>
<nombre>HUGO QUISPE CABRERA</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>62</idcliente>
<nombre>ALEXANDRE LOPEZ (INOX)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>63</idcliente>
<nombre>ALEXANDRA RODRIGUEZ (TARIJA)</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>64</idcliente>
<nombre>ALEXANDER CASTILLO</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>65</idcliente>
<nombre>HUGO PORCO ESTRADA (TARIJA) </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>66</idcliente>
<nombre>HUGO MONTAÑO </nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
<cliente>
<idcliente>67</idcliente>
<nombre>CLIENTE-VARIOS</nombre>
<descripcion></descripcion>
<telefono></telefono>
</cliente>
</dataroot>
